sudo: required
language: rust
cache: cargo
rust:
  - nightly
  - stable
branches:
  except:
    - staging.tmp

# Install ALSA development libraries before compiling on Linux.
addons:
  apt:
    packages:
        - libasound2-dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fc87a993d7683ec8b279
    on_success: change
    on_failure: always
    on_start: never

script:
  - cargo test --no-default-features --features opengl
  - cargo test --all-features
  - cargo doc
# - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then (cargo bench); fi
